library(tidyverse)

# Generated by scripts/downloads/TCGA/download_file_ids_to_aliquots.R
metadata <- readRDS("downloads/TCGA/HLA/file_ids_to_aliquots.rds")
metadata %>%
  mutate(data_type = recode(data_type, "WXS"="DNA-Seq")) %>%
  saveRDS("data/sample_names_tcga.rds")
