library(tidyverse)

# Read in combined gold standard
source("scripts/functions/gold_standard_preprocessing.R")

# G-group mapper script
source("scripts/functions/ggroup_mapper.R")

# Load in the gold standard
# (generated by scripts/combine_1kg_gold_standard.R)
goldStandardLocation <- "temp/GourroudAndDeBakker_gold_standard.txt"
resolutionInDigits <- 4
# Preprocess the gold standard data
goldStandard <- prepareGoldStandard(goldStandardLocation, resolutionInDigits)

# Cleanup the data
# Make a real matrix out of this
goldStandard_data = simplify2array(goldStandard[[3]])
colnames(goldStandard_data) <- make.names(goldStandard[[1]], unique=T)
rownames(goldStandard_data) <- goldStandard[[2]]

# Implementation of allele_map function
# that supports non-unique alleles per sample, gene
ga_map_cell <- function(column) {
  gene <- str_remove(cur_column(), '\\..*')
  map(column, ~unique(ga_map(gene, as.character(.))))
}

df <- as_tibble(goldStandard_data, rownames="sample_id") %>%
  # G-group mapping
  mutate(across(-sample_id, ga_map_cell)) %>%
  gather("locus", "allele", -sample_id) %>%
  unnest(allele) %>%
  # Handle the case where we have multiple g-groups for one sample, locus
  arrange(sample_id, locus, allele) %>%
  group_by(sample_id, locus) %>%
  # Take the first g-group if multiple are present
  group_modify(~head(., 1)) %>%
  ungroup %>%
  mutate(gene=str_remove(locus, '\\.1$')) %>%
  arrange(sample_id, locus) %>%
  group_by(sample_id, gene) %>%
  mutate(locus=paste0(gene, ".", row_number())) %>%
  ungroup %>%
  select(sample_id, locus, allele) %>%
  spread("locus", "allele")

saveRDS(df, "data/gold_standard_1kg.rds")